version: "3.9"

services:
  db:
    build:
      context: ./infra/docker
      dockerfile: postgres.dockerfile
    container_name: people-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: people_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: people-backend
    restart: always
    env_file:
      - .env
    ports:
      - "5000:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: people-frontend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:8080"
    depends_on:
      - backend

volumes:
  postgres_data:
