version: "3.9"

services:
  db:
    build:
      context: ../..
      dockerfile: infra/docker/postgres.dockerfile
    container_name: people-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: people_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../..
      dockerfile: infra/docker/backend.dockerfile
    container_name: people-backend
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ../..
      dockerfile: infra/docker/frontend.dockerfile
    container_name: people-frontend
    restart: always
    env_file:
      - ../../.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
