projectId = "f87cc766-d691-4c74-918d-df5c5f501561"
name = "backend"

[deploy]
installCommand = "pnpm install --no-frozen-lockfile"
buildCommand = "pnpm run build"
startCommand = "node dist/index.js"
numReplicas = 1
restartPolicyType = "ALWAYS"
healthcheckPath = "/api/docs"

[envs]
PORT = "8080"
FEATURE_ENTERPRISE = "false"
FEATURE_AI = "false"
DATABASE_URL = "${{db.DATABASE_URL}}"
