#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Rodando lint..."
pnpm exec eslint . --ext .ts,.tsx --fix || exit 1

echo "🔨 Rodando build..."
pnpm build || exit 1

echo "🧪 Rodando testes..."
pnpm test || exit 1
