name: CI Checks

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: people_analytics
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run migrations
        run: pnpm --filter db migrate

      - name: Run lint
        run: pnpm lint

      - name: Build backend
        run: pnpm --filter backend build

      - name: Run backend tests
        run: pnpm --filter backend test

      - name: Build frontend
        run: pnpm --filter frontend build

      - name: Run frontend tests
        run: pnpm --filter frontend test
